### ISSUE TITLE
Making namespaces a 1st class part of tags

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dqe_idx#6]
I am thinking it might be nice to make namespaces a 1st class citizens of tags, current tags would work with an 'empty'  namespace or a default namespace, but it would allow handing things like metadata, ddb internal tags, automatically added tags without the risk for having collisions.

@davecromberge @szarsti any thoughs?

**Comment by starstuck** [comment]
Good idea!

**Comment by davecromberge** [comment]
Yes I agree, this is a great idea.

**Comment by Licenser** [comment]
Done, with the `ddb` prefix reserved for damatinerdb internal i.e. for globbing yay globbing!
